### ISSUE TITLE
xdebug cannot be installed because the base image has been updated to php8.

### ISSUE THREAD

**Issue by strausmann** [apolopena/gitpod-laravel-starter#155]
### Describe the bug

When updating /etc/php/7.4/apache2/php.ini in the directory used for xdebug configuration, the /etc/php/7.4 directory can no longer be found. The reason for this is the update of the Gitpod base image to PHP 8.

https://github.com/apolopena/gitpod-laravel-starter/blob/a26165e22035f442b4d09607c246b29272875c61/.gitpod.Dockerfile#L26

### Steps to reproduce

After adapting the .gitpod.Dockerfile to your own needs, e.g. updating the root CAs, GitPod cannot build a working Docker image. 
If you leave the .gitpod.Dockerfile unchanged, the existing Docker image can be successfully loaded from the GitPod registry.

**Comment by apolopena** [comment]
Thanks for pointing this out.

**Comment by apolopena** [comment]
Until php 7.4 reaches end of life or at the very least the php 8 adoption rate exceeds that of php 7.4, php7.4 must still be supported by this software. Dynamically (vis starter.ini) supporting different version of php introduces complexities I would rather not address however such is the nature of software engineering. 

This fix will take some time as I will be adding support for `php_version` (either `gitpod_latest` or `7.4.*`) in `starter.ini`.

**Comment by apolopena** [comment]
This issue blocks the entire project as the workspace image fails to build.
This issue depends on feature https://github.com/apolopena/gitpod-laravel-starter/issues/156
