### ISSUE TITLE
starter.ini: Make the PHP version configurable

### ISSUE THREAD

**Issue by apolopena** [apolopena/gitpod-laravel-starter#156]
## Problem this feature will solve
Users are forced to use the version of PHP that the gitpods `workspace-full` image uses. Whenever the version of PHP changes in gitpod `workkspace-full`, this entire project breaks at the `.Dockerfile` level (when the image is built) and will not run. 

## Background

Currently the PHP version in `workspace-full` is version 8.0 which is only about 17% adopted vs the 45%-ish adoption rate of PHP 7.4

## Proposed Solution

Allow the PHP version to be set from `starter.ini` in the `[PHP]` section.
Acceptable values should be:
`7.4` 
`gitpodlatest`

- The `starter.ini` value `7.4` will install PHP 7.4.* **_in addition_** to the latest PHP version and packages as per the gitpod image [workspace-full](https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile) with the following PHP packages:
  - `php7.4 php7.4-fpm php7.4-dev php7.4-bcmath php7.4-ctype php7.4-curl php-date php7.4-gd php7.4-intl php7.4-json php7.4-mbstring php7.4-mysql php-net-ftp php7.4-pgsql php7.4-sqlite3 php7.4-tokenizer php7.4-xml php7.4-zip`
- The `latest' value will install the just version of PHP and its respective packages as per the gitpod image [workspace-full](https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile)

The default value in starter.ini should be this:
```ini
[PHP]
version: 7.4
```
Also dynamically set the PHP API  (extension_dir) xdebug paths and anything else that needs the PHP API path (such as the server function `start_server`). The extensions path for PHP on a debian system can be dynamically obtained with the following command:
```bash
php -r 'echo ini_get("extension_dir");'
```

## Constraints and Assumptions
The Installs for PHP happen at the `.gitpod..Dockerfile` (Docker) level so the PHP version in `starter.ini` will be cached! This means that any change to the PHP version in `starter.ini` will require the docker cache to be cleaned by incrementing the `INVALIDATE_CACHE` value in [`.gitpod..Dockerfile`](https://github.com/apolopena/gitpod-laravel-starter/blob/a26165e22035f442b4d09607c246b29272875c61/.gitpod.Dockerfile#L35)

Depends on https://github.com/apolopena/gitpod-laravel-starter/issues/172

## Alternatives or Workarounds

None worth mentioning

## Additional context
Since the PHP extension path (extension_dir) will now derived dynamically nothing should break when Gitpod updates the version of PHP.

**Comment by apolopena** [comment]
Yeah we can grab the PHP API version (dated folder name of the PHP version currently in use) with this:
```bash
php -i | grep 'PHP API' | cut -f2 -d'>'
```

**Comment by apolopena** [comment]
xdebug extension in `.gitpod.Dockerfile` can be set dynamically:
```bash
echo -e "\nzend_extension = $(php -r 'echo ini_get("extension_dir");')/xdebug.so\n[XDebug]\nxdebug.client_host = 127.0.0.1\nxdebug.client_port = 9009\nxdebug.log = /var/log/xdebug.log\nxdebug.mode = debug\nxdebug.start_with_request = trigger\n"
```

I am looking into consolidating [`.gp/conf/xdebug.ini`](https://github.com/apolopena/gitpod-laravel-starter/blob/main/.gp/conf/xdebug/xdebug.ini) so everything is cleaner and more concise since currently `.gitpod.Dockerfile` writes out the same thing that is in [`.gp/conf/xdebug.ini`](https://github.com/apolopena/gitpod-laravel-starter/blob/main/.gp/conf/xdebug/xdebug.ini)

**Comment by apolopena** [comment]
This approach will also be used in the ioncube install in `init-gitpod.sh` hencing making that feature futureproof against PHP version changes in the `gitpod-full` image.

**Comment by strausmann** [comment]
IonCube does not have PHP 8 support yet. Therefore we have to make sure that ioncube is currently only rolled out if php switch is on 7.4.

**Comment by apolopena** [comment]
I will make a note of thet in the ioncode comments in `starter.ini` and be sure to not install ioncude if php8+ is in use in `init-gitpod.sh`

**Comment by apolopena** [comment]
OK so I have an optional dynamic install of a supported (as per `starter.ini`) PHP version working now. It was not easy mostly because PHP is installed as a module for Apache. 

Now that the optional dynamic install of a supported (as per `starter.ini`) PHP version works though, `ppa:ondrej/php` is used which I dont think should be forced onto the used.

`ppa:ondrej/php` is currently used because this is what is in the underlying image we use: https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile

I will open another feature that allows to user to either install their optional PHP version using the OS version (default) or to use  `ppa:ondrej/php`

**Comment by apolopena** [comment]
Depends on https://github.com/apolopena/gitpod-laravel-starter/issues/172

**Comment by apolopena** [comment]
swapping `latest` to `gitpodlatest` for the sake of clarity

**Comment by strausmann** [comment]
good idea

**Comment by apolopena** [comment]
> I will make a note of that in the ioncobe comments in `starter.ini` and be sure to not install ioncube in `init-gitpod.sh` if php8+/latest is in use

Also working this in now.

**Comment by apolopena** [comment]
ioncube version mismatch ready to test in `development`

**Comment by strausmann** [comment]
what exactly is the default php version for now? 7.4 or ?

**Comment by apolopena** [comment]
yeah `7.4` since it is currently more widely used out in the wild. Once the numbers point the other way I will change it in a future release.

**Comment by strausmann** [comment]
the xdebug config must not be included directly in php.ini. xdebug must always be loaded after the ioncube.

![image](https://user-images.githubusercontent.com/4519228/150653932-f69413e6-3c49-4dbe-922d-0873ddbe728a.png)

therefore xdebug should always be integrated with the 20-xdebug.ini inside the conf.d folder

otherwise you will always get this error when running php.

![image](https://user-images.githubusercontent.com/4519228/150653947-9072c6a9-914a-4c90-9a06-fd94f6ae340a.png)

**Comment by strausmann** [comment]
Must still be checked for true not false.

https://github.com/apolopena/gitpod-laravel-starter/blob/1294ebe5666ba1a26808b5cceebb6af6af9bc32a/.gp/bash/init-gitpod.sh#L212

**Comment by apolopena** [comment]
OK I will fix this today

**Comment by apolopena** [comment]
This is one of those oddly flipped values since the function returns false if the first value is greater than the second but we want that reversed so after testing I think this is the line to use:
```bash
[[ $(bash .gp/bash/utils.sh comp_ver_lt "$php_current_version" "8.0") == 1 ]]
```

**Comment by apolopena** [comment]
> the xdebug config must not be included directly in php.ini. xdebug must always be loaded after the ioncube.

Are you talking about this lhese lines of code?
https://github.com/apolopena/gitpod-laravel-starter/blob/development/.gp/bash/install-xdebug.sh#L30
https://github.com/apolopena/gitpod-laravel-starter/blob/development/.gp/bash/install-xdebug.sh#L31
https://github.com/apolopena/gitpod-laravel-starter/blob/development/.gp/bash/install-xdebug.sh#L32

**Comment by strausmann** [comment]
This Line is corret https://github.com/apolopena/gitpod-laravel-starter/blob/8613f1a0283df503f373c3dca5ddb27693bf2b80/.gp/bash/install-xdebug.sh#L32

But this are the problem.
https://github.com/apolopena/gitpod-laravel-starter/blob/development/.gp/bash/install-xdebug.sh#L44
https://github.com/apolopena/gitpod-laravel-starter/blob/development/.gp/bash/install-xdebug.sh#L45

**Comment by apolopena** [comment]
yeah ok thanks for clarifing. I thought so. I will change them to conf.d rather than directly in the php.ini

**Comment by strausmann** [comment]
and I think this will not work with a PHP8 workspace either.

https://github.com/apolopena/gitpod-laravel-starter/blob/8613f1a0283df503f373c3dca5ddb27693bf2b80/.gp/bash/install-xdebug.sh#L40

Would have to be phpize8.0

**Comment by apolopena** [comment]
Yeah 

> and I think this will not work with a PHP8 workspace either.
> 
> https://github.com/apolopena/gitpod-laravel-starter/blob/8613f1a0283df503f373c3dca5ddb27693bf2b80/.gp/bash/install-xdebug.sh#L40
> 
> Would have to be phpize8.0

Yeah I will make that dynamic

**Comment by apolopena** [comment]
alright its close. xdebug and ioncube gets properly installed fro php 7.4 all dynamically. Dynamic phpize works too. 

Retaining the existing php version using an invalid value or `gitpodlatest` is not working (its installing 7.4 no matter what) and the error: about php_fpm_conf or whtever it was is still occuring.

I have to step away for the rest of the day. I will pick this back up this evening or tomorrow morning.

**Comment by apolopena** [comment]
Test success
ioncube will not be installed if php version > 7.4
![image](https://user-images.githubusercontent.com/3060702/150731331-0df50e4a-0620-445a-8778-78aff344fef6.png)

**Comment by apolopena** [comment]
Test success
System falls back to `gitpodlatest` version of PHP if an invalid/unsupported value is set in starter.ini
![image](https://user-images.githubusercontent.com/3060702/150731662-a1ba91b1-4f29-44ff-8419-3a91023a3af2.png)

**Comment by apolopena** [comment]
Test success
The appropriate version of phpfpm is installed in `install-core-packages.sh` if the currently installed version of PHP greater than 7.4
![image](https://user-images.githubusercontent.com/3060702/150731975-0fc90d33-8980-4e74-98cb-959fc6e5ae9f.png)

**Comment by apolopena** [comment]
Test success
**php 7.4** and **php7.4-fpm** is successfully installed. existing version of php ('gitpodlatest') is purged and `ppa:ondrej/php` is remove when `ppa=OS`  (and `version` is less than 8.0) in s`tarter.ini`. **ioncube** is also successfully installed when `[ioncube] install=1`
xdebug is also properly downloaded compiled installed (and dynamically) php, php cli, and php-fpm
![image](https://user-images.githubusercontent.com/3060702/150732988-27833167-f01c-4ff9-a93d-8aecfa9a62c9.png)
![image](https://user-images.githubusercontent.com/3060702/150733637-72925b0e-62f1-4d5d-b183-aa5f0f42aa0f.png)
![image](https://user-images.githubusercontent.com/3060702/150733846-50377bcd-c0a1-4fda-a198-c09337a8eb05.png)

**Comment by apolopena** [comment]
I accidentally commited the built version of the project from gitpod which makes quite a mess.
I had to force revert the development branch to commit `cf01bdf180cc0927655461fffd853d97969f0fd7`

Long story short. Please make sure you create a new development branch in your fork to avoid any issue when you test.

Feel free to test the items I mentioned above with screenshots if you like.

Lastly I will work on the last remaining issues #170 and #176 now. Hopefully all this dynamic php installation and config, ppa, ioncobe and xdebug is solid now. Looks that way to me.

**Comment by strausmann** [comment]
@apolopena 
all your changes look very good to me. i have not been able to find any errors now either.
Thank you for your great work
