### ISSUE TITLE
Add an option in starter.ini to generate a phpinfo.php to /public

### ISSUE THREAD

**Issue by apolopena** [apolopena/gitpod-laravel-starter#168]
## Problem this feature will solve

A phpinfo.php page must be created manually in `public/` when debugging PHP extensions and PHP versions and PHP packages.
```php
<?php phpinfo( ); ?>
```

## Background

A phpinfo page for a php project increases the DevX.
## Proposed Solution

Add a name value pair in the `[PHP]` section of `starter.ini`. The default value should be 1 (yes):
`generate_phpinfo=1`
If a value is set to anything other than `1` then do not generate a `phpinfo.php` file in `public/`
## Constraints and Assumptions
<! -- Any constraints and/or assumption relevant for the development and use of this feature? -->

## Alternatives or Workarounds

Add a `phpinfo.php` page to `/public` manually each time you create a workspace for a project.

**Comment by strausmann** [comment]
![image](https://user-images.githubusercontent.com/4519228/150649148-c4a0bbcd-a149-47a8-8bd4-ba579209acff.png)

**Comment by apolopena** [comment]
Yeah I added a space to the log message to try to fix that. Sometimes the spinner chops off a character.

**Comment by strausmann** [comment]
ah ok, known issue :-)
