### ISSUE TITLE
Add GnuPG Support to sign git commits

### ISSUE THREAD

**Issue by strausmann** [apolopena/gitpod-laravel-starter#170]
## Problem this feature will solve

The signing of Git commits currently has to be set up again each time the workspace is restarted.

## Background

Restarting the workspace does not preserve the local information of the workspace, thus the GPG Privatekey and the Git Config are not preserved.

## Proposed Solution

With the start of the workspace, the Git configuration should want to automatically sign each commit and the GnuPG private key is imported into the workspace. So that with a Git commit only the password of the GPG key is requested and the commit is signed with it.

## Constraints and Assumptions

- GPG support should only be set up if GPG_KEY and GPG_KEY_ID are stored in the Gitpod environments.
- The GPG private key should be Base64 encoded in the GitPod environments.
- GPG signed commits will not be marked as `verified` in the github UI if the email ~/.gitconfig doesnt match that of the GPG key.

## Alternatives or Workarounds

Since this is not a rarely relevant feature, a project-based implementation is less likely to be considered if necessary.

**Comment by apolopena** [comment]
@strausmann For documentation and testing can you give an example of the proper values for `$GNUPG_KEY` and `$GNUPG_SIGNING_KEY`?

**Comment by apolopena** [comment]
I merged in your changes to the `development` branch and enhanced them, now I would like to test and document this great feature.

**Comment by apolopena** [comment]
Depends on https://github.com/apolopena/gitpod-laravel-starter/issues/176

**Comment by apolopena** [comment]
@strausmann ready to test in the `development` branch
https://gitpod.io/#/https://github.com/apolopena/gitpod-laravel-starter/tree/development

**Comment by strausmann** [comment]
Could be used successfully even after several restarts of the workspace.

![image](https://user-images.githubusercontent.com/4519228/150640485-44cdfd7d-6e9a-4094-9f6c-060d0decbfdc.png)

**Comment by apolopena** [comment]
Awesome. Perhaps we should quiet the gpg `stdout` and only show `stderr` since we have so much output already. We report on SUCCESS or ERROR already. What do you think?

**Comment by strausmann** [comment]
I like, I had also already considered

**Comment by apolopena** [comment]
Great. I just added that in blind. Test if you like.

**Comment by strausmann** [comment]
Does not work as expected https://github.com/apolopena/gitpod-laravel-starter/commit/36149918059bc56bdf65337b210eacb688ac9fee

**Comment by apolopena** [comment]
Ok please try again

**Comment by strausmann** [comment]
Looks better...

![image](https://user-images.githubusercontent.com/4519228/150651502-9e3acc77-1b9d-4c03-bdbc-9d57c966a3d0.png)

**Comment by strausmann** [comment]
![image](https://user-images.githubusercontent.com/4519228/150651790-59d3c8eb-688f-4794-ad56-5bf04b19b1fe.png)

**Comment by apolopena** [comment]
I am pretty sure this existed before my fix for supressing output. Please revert those fixes and run `git log --show-signature -1`  again to verify.

**Comment by strausmann** [comment]
All good, this was the output of  <code>git log --show-signature -1</code>
just wanted to clarify that now signing works again.

**Comment by apolopena** [comment]
oh ok, haha. It looked like a failure with that warning but I take it that is because the key you are testing with is just a dummy. If you used your true key would the warning go away?

**Comment by apolopena** [comment]
Yeah so the last thing on the list before release is https://github.com/apolopena/gitpod-laravel-starter/issues/176. Please see my last comment.

**Comment by apolopena** [comment]
oh yeah the intellisense feature needs to be documented in the README as well. I will add that to #176

**Comment by strausmann** [comment]
> git log --show-signature -1

No, even with my own key the warning is not gone, because after importing the key, you would still have to set it trusted.

You would have to execute an edit-key interactively to trust the key.

But everything ok. You still need the passphrase for the private key anyway.

**Comment by apolopena** [comment]
> You would have to execute an edit-key interactively to trust the key.

Can you give me this or a link that shows how its done so I can put it in the documentation?

**Comment by strausmann** [comment]
yes, sure.

https://blog.tersmitten.nl/how-to-ultimately-trust-a-public-key-non-interactively.html

**Comment by apolopena** [comment]
Renaming `GNUPG_SIGNING_KEY` to `GPG_KEY_ID` and `GNUPG_KEY` to `GPG_KEY`, will document this in https://github.com/apolopena/gitpod-laravel-starter/issues/176

**Comment by apolopena** [comment]
GPG Key for git commit signing is implemented properly and logged however pushes to remote still show up as unverified.

**Comment by apolopena** [comment]
This is related to the fact that a GPG key can have an email address that doesn't match the git commiters address such as in the case where a github no-reply email address is used such as `3060702+apolopena@users.noreply.github.com`

**Comment by apolopena** [comment]
I will add support for a third environment variable: `GPG_FORCE_GIT_EMAIL_TO_MATCH`
The value should be set to the email that your GPG key uses.
Setting this environment variable will force `~/.gitconfig` to be parsed with the value of `GPG_FORCE_GIT_EMAIL_TO_MATCH`

**Comment by apolopena** [comment]
I will add support for a fourth environment variable: `$GPG_AUTO_ULTIMATE_TRUST`
If the value is set to `yes` or `YES` then the `GPG_KEY` with `GPG_KEY_ID` will be programatically given ultimate trust.
