### ISSUE TITLE
Update README with information about configuring GPG keys and Intelliphense

### ISSUE THREAD

**Issue by apolopena** [apolopena/gitpod-laravel-starter#176]
Document https://github.com/apolopena/gitpod-laravel-starter/issues/170 and https://github.com/apolopena/gitpod-laravel-starter/issues/165 in the README

**Comment by strausmann** [comment]
Here you can find a small tutorial, you can take over the steps.

https://adangel.org/2021/11/07/gitpod-gpg-signed-commits/

**Comment by strausmann** [comment]
Could be used successfully even after several restarts of the workspace.

![image](https://user-images.githubusercontent.com/4519228/150640485-44cdfd7d-6e9a-4094-9f6c-060d0decbfdc.png)

**Comment by apolopena** [comment]
> Here you can find a small tutorial, you can take over the steps.
> 
> https://adangel.org/2021/11/07/gitpod-gpg-signed-commits/

This makes no reference to the second variable we arre using `$GNUPG_SIGNING_KEY` so I am unsure how to document this. I would just link to ttps://adangel.org/2021/11/07/gitpod-gpg-signed-commits/ from the README if we didnt have that second variable.

Also this line of code is not in the reference link:
`git config --global user.signingkey "$GNUPG_SIGNING_KEY"`

**Comment by apolopena** [comment]
This is the last issue we have to resolve before a final test and release, yay!

**Comment by strausmann** [comment]
> 
<code>GNUPG_SIGNING_KEY</code> is the key ID, you get it with the command <code>gpg --list-keys --keyid-format LONG</code>

![image](https://user-images.githubusercontent.com/4519228/150654617-4f177923-43f0-48b5-9366-4a179dfd69b7.png)

**Comment by apolopena** [comment]
OK 
Any idea why the refence link doesnt use that value but we do?

**Comment by strausmann** [comment]
if you have other subkeys, you can use them to specify exactly which one you want to use. Which is true in my case.

**Comment by strausmann** [comment]
or else you would have to specify it in the commit command apparently.

git commit -S[<keyid>] flag (a.k.a. git commit --gpg-sign[=<keyid>])

**Comment by apolopena** [comment]
Ah so `GNUPG_SIGNING_KEY` is the key ID and `GNUPG_KEY` is the base64 encoded key itself?

If this is the case is  `GNUPG_SIGNING_KEY` optional? because I made it required in the code. If `GNUPG_SIGNING_KEY` was not required what would happen if a user had `GNUPG_KEY` set but `GNUPG_SIGNING_KEY` was not set. 

would it be best to just leave it as is and keep `GNUPG_SIGNING_KEY` required. 

Either way if `GNUPG_SIGNING_KEY` is an ID for they key and `GNUPG_KEY` is the key itself then the variable names should be changed to reflect that: `GNUPG_SIGNING_KEY_ID` and `GNUPG_SIGNING_KEY` respectively ya?

**Comment by strausmann** [comment]
I would leave it as mandatory and welcome your renaming of the variables.

**Comment by apolopena** [comment]
ok will do

**Comment by apolopena** [comment]
Added a section to the README for Gitpod Environment Variables. This will be where ew document any special action the starter will take when it encounters certain environment variables.
