### ISSUE TITLE
Question about Database Migration 

### ISSUE THREAD

**Issue by strausmann** [apolopena/gitpod-laravel-starter#182]
Why is a database migration not automatically performed at the end? Is there a reason why this does not happen in the standard?

https://github.com/apolopena/gitpod-laravel-starter/blob/acf39fe45557248c125c1b64700f41ba0941df54/.gp/bash/init-project.sh#L10-L23

**Comment by apolopena** [comment]
By default when a starter is created there is nothing to migrate right? Also if a user uses a preset in the workspace URL then migrations will happen there and so we dont want to do redundant migrations.

I figure that once a user has something to migrate they will enable it themselves but now that you mention it I do see that that is one extra step they wouldnt have to do. Thoughts?

**Comment by apolopena** [comment]
I will add a migration section to the README and talk about typical Laravel migration and seeding setups using `.gp/bash/init-project.sh` such as what is used in some of the presets (example projects) such as: 
https://gitpod.io/#EXAMPLE=1/https://github.com/apolopena/gitpod-laravel-starter
that uses
https://github.com/apolopena/qna-demo-skeleton/blob/main/.gp/bash/init-project.sh

**Comment by apolopena** [comment]
Moved to #183
