### ISSUE TITLE
Restarting a workspaces gives an error when opening the preview

### ISSUE THREAD

**Issue by apolopena** [apolopena/gitpod-laravel-starter#19]
### Describe the bug
restarting a workspaces gives an intermittent error when opening the preview:
```
2021/02/03 16:16:18 error while issuing request: Post "http://localhost:23000/gitpod/cli": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/02/03 16:16:53 error while issuing request: Post "http://localhost:23000/gitpod/cli": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Steps to reproduce

1. create a new workspace
2. stop the workspace
3. restart the workspace

### Expected behavior
There should be no errors

### Additional information
Looks like the preview browser is trying to open again when its already open.

**Comment by apolopena** [comment]
Seems to be intermittant. So far I can't replicate it.

**Comment by apolopena** [comment]
The issue has disappeared. I will re-open it if anyone sees it again.

**Comment by apolopena** [comment]
seeing this again

**Comment by apolopena** [comment]
Seems internal to gitpod. Will follow up later.

**Comment by apolopena** [comment]
See: https://github.com/gitpod-io/gitpod/issues/3178

**Comment by apolopena** [comment]
The bug happens when `gp preview` is called from a 'reused' terminal on workspace restart  and the browser is already open. This was hanging the spinner and genrally causing havok with the dely and multiple preview refresh.

I implemented a workaround that stops the spinner before the `gp preview` call, also I did away with the open preview function and just put the logic directly in `.gitpod.yml`. The result is no hung terminal and just one long delay and error message upon workspace restart when the browser window is already open. no errors seen so far upon workspace init.

Untested with VsCode as they are still working on implementing `gp preview` for VSCode.
```
error while issuing request: Post "http://localhost:23000/gitpod/cli": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by apolopena** [comment]
Further tests show that the error happens even when the preview browser is closed before the workspace is stoped and then started again.
This is definitely a gitpod internal bug. I will keep it open but consider the bug worked around as best as possible which actaully is not t a very good user experience.

The only real workaround might be to only open the preview browser on init instead of trying to do it in a reused terminal on every workspace restart.

**Comment by apolopena** [comment]
Spinner no longer corrupts the terminal. Still odd behavior on workspace restart in the terminal that opens the preview however it is no longer fatal. Click into the terminal after some time if the terminal looses its prompt.

**Comment by ivelin** [comment]
Experiencing this same error:

https://brown-tiglon-cmqn0u85.ws-us03.gitpod.io/#/workspace/ambianic-docs

https://github.com/ambianic/ambianic-docs/blob/master/.gitpod.yml

**Comment by apolopena** [comment]
There are two decent workarounds for this issue until it is fixed by Gitpod.

- Move the command  `gp await-port 8000 && gp preview $(gp url 8000)` to the last piece of code executed from the `init `command.

**Or**

- Remove the `gp await-port 8000 && gp preview $(gp url 8000)` from `.gitpod.yml` replace it with a port directive:
```yml
ports:
- port: 8000
  onOpen: open-preview
```

**Comment by apolopena** [comment]
I implmented a hotfix for gracefully handling the gp preview Gitpod internal error
```yml
command: |
      if bash .gp/bash/open-preview.sh; then exit; else bash .gp/bash/hotfix.sh; fi
```

**Comment by apolopena** [comment]
Renamed `hotfix.sh` to `patch-preview.sh`
