### ISSUE TITLE
settings.json, php-conf.php should only be parsed when the project is bootstrapped

### ISSUE THREAD

**Issue by apolopena** [apolopena/gitpod-laravel-starter#196]
### Describe the bug

`.vscode/settings.json` and `.gp/conf/php-fpm/php-fpm.conf` will get overwritten once they are bootstrapped (built for the first time).

### Steps to reproduce

1. Create a new repo from this repo
2. Create a new Gitpod workspace from the new repo
3. Make some changes in `.vscode/settings.json` and `.gp/conf/php-fpm/php-fpm.conf`
4. Save all changes to the remote repo
5. Build a new workspace from the new repo

Observe that the changes made to  `.vscode/settings.json` and `.gp/conf/php-fpm/php-fpm.conf` in step 3 are gone.

### Expected behavior

Chnage made to  `.vscode/settings.json` and `.gp/conf/php-fpm/php-fpm.conf` after a project is bootstrapped should remain

**Comment by strausmann** [comment]
Each time you load the project in with a GitPod workspace, the two lines are added again.

![image](https://user-images.githubusercontent.com/4519228/152661029-3b089e3c-9076-4ed6-8a16-35984a873c9d.png)

**Comment by apolopena** [comment]
I will get a patch release out for this ASAP.
